### ISSUE TITLE
Pushing item with ID should update existing item

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/SQL_Toolkit#17]
If pushing an object with an ID, and a push type set to some form of update, then we should check if an existing item with that ID exists and update its data. If an existing item doesn't exist, then insert.

**Comment by tg359** [comment]
Would it be possible to use EntityFramework to handle a lot of the object to/from SQL management? From what I've read it should just be a case of telling it to upsert an object to a table, and given that it's in EntityFramework all of the handling of that object is done automagically.

**Comment by FraserGreenroyd** [comment]
EntityFramework would definitely be a good way to go, @adecler is there any particular reason why we've opted to avoid using the EntityFramework in the original makings of the toolkit?

I've found an `UpdateCommand` option within the Toolkit which suggests by its name to do what I need it to but is going to be rather unruly within the framework I'm working in.

I might prototype up a version of the adapter using EntityFramework later just to see what the impact is on the code/usability for discussion, depends how much further I get with some of the other items instead :smile:

**Comment by adecler** [comment]
I am not sure I agree with this issue. @FraserGreenroyd , can you provide some context and reasons to do this ?
Remember that the plan is to migrate the soft-delete solution used in BuildingPerformance and EmbodiedCarbon to the SQL toolkit itself. So the idea is to never update directly any table row (other than marking it as deleted).

**Comment by FraserGreenroyd** [comment]
The analytics data being scraped for code analytics has data which changes the state of objects in the database. Having duplicate rows of data (as is currently happening) isn't desirable as it's a similar state change as `deleted`. That and this is a SQL_Toolkit, so should probably handle (in my view) SQL operations suitable for general SQL use rather than specific SQL implementation for specific actions.

That's where I think using the EntityFramework might benefit us in the long run. It makes interactions with SQL and C# objects reasonably straight forward (in my view at least, though I acknowledge I have a lot of experience with using it and so will have a bias towards it), and setting up object tables is generally just a case of registering the types. However, it may be that for the complexity of BHoM objects that may not be suitable, but for the database objects that I think we're currently working with (for analytics, and upcoming projects from MEP with @Georgios-Grigoriou , etc.) it might bring benefit.

I think there are ways where we can keep both uses of SQL, as I know there's discussion on the use of primary keys in #5 which may restrict what the options are to achieve what all the use cases need. I'm hitting roadblocks on most of the code analytics scrape as it turns out anyway, this is just one of them I need to try and overcome to close out that loop 😖
