### ISSUE TITLE
Complete initial setup for the SQL Toolkit repo

### ISSUE THREAD

**Issue by adecler** [BHoM/SQL_Toolkit#3]
I have updated the readme file and modified the master branch settings to make sure it can only be merged to master after review. 
Form the top of my head there's a few other things that need to be done for the repo to be compliant:
- Get the `build` and `Azure pipeline` checks at the top of the readme.
- link to CI/CD checks required for repos that are not currently on the installer
- Agree on who is part of the SQL_Toolkit team
- Set the milestones (labels are already in). I guess that one can wait next milestone and be done with the others
- Anything else I forgot ?

**Comment by FraserGreenroyd** [comment]
> * Get the `build` and `Azure pipeline` checks at the top of the readme.

I don't intend for us to get Azure stuff on this repo unless there's a big push for it, we're now moving into BHoMBot usage across things more.

> * link to CI/CD required for repos that are not currently on the installer

BHoMBot should already work with the usual commands providing the `dependencies.txt` file is set up correctly.

> * Agree on who is part of the SQL_Toolkit team

I'd say the 3 of us on the team for merging is appropriate

> * Set the milestones (labels are already in). I guess that one can wait next milestone and be done with the others

Agreed, we'll be doing more milestones as we close out this beta :smile:

**Comment by adecler** [comment]
Thanks @FraserGreenroyd , I've pushed the `dependencies.txt` file on the PR and added you two to the SQL team
