### ISSUE TITLE
Primary key or no primary key?

### ISSUE THREAD

**Issue by tg359** [BHoM/SQL_Toolkit#5]
Are we storing the BHoM_Guid as the primary key? I think it would make sense to as it's guaranteed to be unique. A related question is [HERE](https://github.com/BHoM/SQL_Toolkit/issues/4) about structure of tables given the need for type-strong storage.

**Comment by al-fisher** [comment]
I think the answer to this will depend on the context and workflow to be achieved.

In the first instance we are naturally using SQL to store objects representing results, analytics, facts and flat data etc. playing to its strengths.
In terms of objects in the BHoM, this maps most closely to our [`IResult` object](https://github.com/BHoM/BHoM/blob/37c8ae1d1afc84cbc0d1c0103c2d1969f97b7019/Analytical_oM/Results/IResult.cs#L32) which implements `IObject` and not `IBHoMObject` - and thus does not have the property `BHoM_Guid`.

Thus for the primary key on a item in a central "Fact" table I might be tempted to look in the first instance as setting as a simple integer, allocated incrementally on generation - (which effectively corresponds to the table row, and thus ensures uniqueness that way, but does not really need to be any more sophisticated than this)

For other objects whose Primary Key will be referenced as a Foreign Key in another table, BHoM_Guid _could_ make sense.
But again there might actually be another more useful/logical property to use - which might not actually be a Guid. 
Using `IResult` as an example again - both [`ObjectID`](https://github.com/BHoM/BHoM/blob/37c8ae1d1afc84cbc0d1c0103c2d1969f97b7019/Analytical_oM/Results/IResult.cs#L38) and [`ResultCase`](https://github.com/BHoM/BHoM/blob/37c8ae1d1afc84cbc0d1c0103c2d1969f97b7019/Analytical_oM/Results/IResult.cs#L40) will be Primary Keys for the Object and ResultCase dimensions. These in many practical cases could also be integers (results pulled from analysis models) - or strings (which are more human readable and useful than a Guid) 

This the answer therefore might be - 
a) will depend on workflow, so will be good to answer based on our specific objects you are dealing with. (LCA_Results/Meter_Data etc.)
b) might rely on BHoM_Guid only in the absence of something better.

Thoughts?

**Comment by al-fisher** [comment]
Let's map out as a diagram the Dimensional Model and relationships between the specific objects (facts and dimensions) we are wanting to store for the very specific workflows currently targeting; and I think that will help answer the question of which Properties should be used for which purpose.
Hope that might help? 😄

**Comment by tg359** [comment]
Closed as no longer relevant following changes to how BHoM objects are stored in SQL DBs.
